services:
  jetson-sensor-ingestion:
    build: ./jetson
    container_name: jetson-sensor-ingestion
    network_mode: host
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: uv run python3 -m sensor_ingestion.ingest_gi
    restart: unless-stopped

  jetson-fusion:
    build: ./jetson
    container_name: jetson-fusion
    network_mode: host
    runtime: nvidia
    privileged: true
    environment:
      - FUSION_HOST=0.0.0.0
      - FUSION_PORT=8050
      - BACKEND_INCIDENT_ENDPOINT=http://127.0.0.1:8000/incidents
      - RUSTFS_ENDPOINT=http://127.0.0.1:9000
      - RUSTFS_PUBLIC_BASE_URL=http://127.0.0.1:9000
      - RUSTFS_BUCKET=drone-detection
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_SKIP_BOOTSTRAP=true
    command: uv run python3 -m ml.fusion_service
    restart: unless-stopped

  jetson-inference:
    build: ./jetson
    container_name: jetson-inference
    network_mode: host
    runtime: nvidia
    privileged: true
    volumes:
      - ./offline_ml/weights:/app/offline_ml/weights:ro
    environment:
      - FUSION_ENDPOINT=http://127.0.0.1:8050/fusion/ingest
      - ZMQ_FRAME_CONNECT_ENDPOINT=ipc:///tmp/frames_bus
      - RGB_MODEL_PATH=/app/offline_ml/weights/visual_no_augmentation_best.pt
      - THERMAL_MODEL_PATH=/app/offline_ml/weights/thermal_no_augmentation_best.pt
    command: uv run python3 -m ml.inference
    restart: unless-stopped

